apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: aksdemob6961972.azurecr.io/demo-app
  newTag: c81d9d968e9210c4b97e056f312a6b39fc40a5ed
