apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: aksdemob6961972.azurecr.io/demo-app
  newTag: c930a27d2993b01477f76a14227e6143d8b1f3d0
